### ISSUE TITLE
Size Mismatch Error for Encoders 

### ISSUE THREAD

**Issue by eotamis** [smthemex/ComfyUI_InstantIR_Wrapper#10]
Some weights of the model checkpoint were not used when initializing CLIPTextModel:
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  7.74it/s]

!!! Exception during processing !!! Error(s) in loading state_dict for GitModel:
        size mismatch for encoder.layer.0.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.0.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.1.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.1.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.2.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.2.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.3.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.3.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.4.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.4.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.5.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.5.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
Traceback (most recent call last):
  File "D:\pinokio\api\comfyui.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\pinokio\api\comfyui.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\pinokio\api\comfyui.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\pinokio\api\comfyui.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 98, in main_
    model = instantIR_load_model(use_clip_encoder, vision_encoder_path, sdxl_path, adapter_path,
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_InstantIR_Wrapper\utils.py", line 125, in instantIR_load_model
    load_adapter_to_pipe(
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_InstantIR_Wrapper\module\ip_adapter\utils.py", line 110, in load_adapter_to_pipe
    AutoModel.from_pretrained(image_encoder_or_path)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\transformers\modeling_utils.py", line 4224, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\transformers\modeling_utils.py", line 4784, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for GitModel:
        size mismatch for encoder.layer.0.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.0.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.1.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.1.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.2.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.2.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.3.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.3.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.4.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.4.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for encoder.layer.5.attention.output.dense.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for encoder.layer.5.attention.output.dense.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

Prompt executed in 13.50 seconds
![Screenshot 2024-11-11 165154](https://github.com/user-attachments/assets/eb106f77-99f7-4a44-bc46-ed397280b38f)

**Comment by smthemex** [comment]
make sure  choice a correct dino repo id ，It‘s look like your [Dino  repo ](https://huggingface.co/facebook/dinov2-large) is not a correct choice.  
or change other SDXL base model.

**Comment by eotamis** [comment]
thanks, provided the .bin file rather than the .safetensors and included .json files in the provided link. Looks like it's working but ~80seconds/iteration on 8GB 3070Ti seems still a lot.. and slower than other methods. I hope this could be fine tuned in the near future. Heads up for your hard work!

**Comment by smthemex** [comment]
I'm glad to see that 8GB of VRAM can run now. It seems that my code modification yesterday was successful

**Comment by smthemex** [comment]
I need some time to disassemble its pipeline. Decomposing and loading it will reduce a lot of unnecessary VRAM usage

**Comment by ReinerBforartists** [comment]
Regarding the dino_repo, it would be nice to have a path picker instead of the value box. The manual copy and paste of the path is a bit uncomfortable.

**Comment by smthemex** [comment]
如果你第一次使用保持repo为默认的路径（facebook/dinov2-large），会自动下载到comfyUI/models/InstantIR/dino 下，并不需要复制粘贴。
If you use the default path for keeping repo (111) for the first time, it will be automatically downloaded to comfyUI/models/InstantIR/dino without the need to copy and paste。
