### ISSUE TITLE
Input type (struct c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by AJbeckliy** [smthemex/ComfyUI_InstantIR_Wrapper#2]
# ComfyUI Error Report
## Error Details
- **Node Type:** InstantIR_Sampler
- **Exception Type:** RuntimeError
- **Exception Message:** Input type (struct c10::Half) and bias type (float) should be the same
## Stack Trace

This error does not occur every time. It is an error that may occur when switching images. However, it is impossible to determine which type of image it is. That is, for the same image, sometimes it can run through without errors, and sometimes an error will occur.
Hope to get your reply.

**Comment by lakge-AI** [comment]
Using a lightning model can solve your problems

**Comment by smthemex** [comment]
can you reply more detail ？  I just fix a little bug  when using low ram..

**Comment by FanXiangTM** [comment]
> Try updating COMFYUI to the latest version!

I also encountered the same problem，I have attempted to update ComfyUI to the latest version，New prompts appear：The size of tensor a (23) must match the size of tensor b (22) at non-singleton dimension 2

**Comment by smthemex** [comment]
Show your console error , I can't help you fix it if you just show this simply error.

**Comment by Shihiu-Lin** [comment]
!!! Exception during processing !!! Input type (struct c10::Half) and bias type (float) should be the same
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 144, in main
    ouput_img = instantIR_main(image_list, model, seed, creative_restoration, steps, prompt, negative_prompt, cfg,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\utils.py", line 185, in instantIR_main
    image = pipe(
            ^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\pipelines\sdxl_instantir.py", line 1392, in __call__
    image = self.vae.encode(image).latent_dist.sample()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 271, in encode
    h = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\autoencoders\vae.py", line 143, in forward
    sample = self.conv_in(sample)
             ^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

Prompt executed in 2.93 seconds
![screenshot](https://github.com/user-attachments/assets/b49d8e4f-1914-496a-af02-fd76d1b61efd)

**Comment by smthemex** [comment]
Replace the previous image scaling, I speculate it may be caused by a mismatch between the vector data type half of the previous scaling and the float32 of VAE. I actually have built-in image cropping in the node
替换掉前置的图片缩放,我推测可能是前置缩放的向量数据类型half跟vae的float32不匹配造成的，我在节点里面其实内置了图片裁切的

**Comment by Shihiu-Lin** [comment]
> Replace the previous image scaling, I speculate it may be caused by a mismatch between the vector data type half of the previous scaling and the float32 of VAE. I actually have built-in image cropping in the node 

I turn off [use_clip_encoder]，The InstantIR_Sampler is work.

**Comment by smthemex** [comment]
change use_clip_encoder will result in different outcomes, and the quality may be better. I will change it to default to off in a certain update.
