### ISSUE TITLE
InstantIR_Loader click low_vram, InstantIR Sampler gets error: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

### ISSUE THREAD

**Issue by 2002erlinglinger** [smthemex/ComfyUI_InstantIR_Wrapper#3]
I'm running a basic workflow (as attached file), when I encounter this issue. If I turn on the low vram in InstantIR Loader, the InstantIR Sampler gets error.  My computer has 8G vram. If I don't turn on low vram in the loader, the loader can't continue. I can't find any solution for this. Does anyone know how to solve it if I don't buy a new video card with larger vram?
[test instantIR.json](https://github.com/user-attachments/files/17671241/test.instantIR.json)

# ComfyUI Error Report
## Error Details
- **Node Type:** InstantIR_Sampler
- **Exception Type:** RuntimeError
- **Exception Message:** Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
## Stack Trace
```
  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 147, in main
    ouput_img = instantIR_main(image_list, model, seed, creative_restoration, steps, prompt, negative_prompt, cfg,

  File "C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper\utils.py", line 175, in instantIR_main
    image = pipe(

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper\pipelines\sdxl_instantir.py", line 1518, in __call__
    cross_attention_emb = self.unet.time_embedding(cross_attention_t_emb, timestep_cond)

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\embeddings.py", line 376, in forward
    sample = self.linear_1(sample)

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** C:\sd-ComfyUI-aki-v1.3\main.py --auto-launch --preview-method auto --disable-smart-memory --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589279232
  - **VRAM Free:** 2832464048
  - **Torch VRAM Total:** 4630511616
  - **Torch VRAM Free:** 78903472

## Logs
```
2024-11-08 09:31:59,497 - root - INFO - Total VRAM 8191 MB, total RAM 65345 MB
2024-11-08 09:31:59,497 - root - INFO - pytorch version: 2.4.1+cu124
2024-11-08 09:32:00,339 - root - INFO - xformers version: 0.0.28.post1
2024-11-08 09:32:00,339 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-08 09:32:00,340 - root - INFO - Disabling smart memory management
2024-11-08 09:32:00,340 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
2024-11-08 09:32:00,449 - root - INFO - Using xformers cross attention
2024-11-08 09:32:01,249 - root - INFO - [Prompt Server] web root: C:\sd-ComfyUI-aki-v1.3\web
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path checkpoints C:/sd-webui-aki-v4.8/models/Stable-diffusion
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path configs C:/sd-webui-aki-v4.8/models/Stable-diffusion
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path vae C:/sd-webui-aki-v4.8/models/VAE
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path loras C:/sd-webui-aki-v4.8/models/Lora
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path loras C:/sd-webui-aki-v4.8/models/LyCORIS
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path upscale_models C:/sd-webui-aki-v4.8/models/ESRGAN
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path upscale_models C:/sd-webui-aki-v4.8/models/RealESRGAN
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path upscale_models C:/sd-webui-aki-v4.8/models/SwinIR
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path embeddings C:/sd-webui-aki-v4.8/embeddings
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path hypernetworks C:/sd-webui-aki-v4.8/models/hypernetworks
2024-11-08 09:32:01,249 - root - INFO - Adding extra search path controlnet C:/sd-webui-aki-v4.8/models/ControlNet
2024-11-08 09:32:03,775 - root - INFO - Total VRAM 8191 MB, total RAM 65345 MB
2024-11-08 09:32:03,775 - root - INFO - pytorch version: 2.4.1+cu124
2024-11-08 09:32:03,775 - root - INFO - xformers version: 0.0.28.post1
2024-11-08 09:32:03,775 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-08 09:32:03,775 - root - INFO - Disabling smart memory management
2024-11-08 09:32:03,776 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
2024-11-08 09:32:15,150 - root - INFO - 
Import times for custom nodes:
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\websocket_image_save.py
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyUI_TJ_NormalLighting
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-FluxExt-MZ
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IC-Light-Native
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\cg-use-everywhere
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Cutoff
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_3dPoseEditor
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantID
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AutomaticCFG
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyui-inpaint-nodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DDColor
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyQR-scanning-nodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyQR
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-KJNodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IC-Light
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_essentials
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
2024-11-08 09:32:15,150 - root - INFO -    0.0 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-SUPIR
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyui-reactor-node
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\PuLID_ComfyUI
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyui_segment_anything
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_tools
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
2024-11-08 09:32:15,150 - root - INFO -    0.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet
2024-11-08 09:32:15,150 - root - INFO -    0.2 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle
2024-11-08 09:32:15,150 - root - INFO -    0.2 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUi-Ollama-YN
2024-11-08 09:32:15,150 - root - INFO -    0.4 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
2024-11-08 09:32:15,150 - root - INFO -    0.5 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
2024-11-08 09:32:15,150 - root - INFO -    0.5 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-clip-interrogator
2024-11-08 09:32:15,150 - root - INFO -    0.6 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-08 09:32:15,150 - root - INFO -    0.9 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\comfyui-liveportrait
2024-11-08 09:32:15,150 - root - INFO -    2.7 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI-PMRF
2024-11-08 09:32:15,150 - root - INFO -    3.1 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-08 09:32:15,150 - root - INFO -    3.2 seconds: C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Segment_Mask
2024-11-08 09:32:15,150 - root - INFO - 
2024-11-08 09:32:15,177 - root - INFO - Starting server

2024-11-08 09:32:15,178 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-08 09:33:01,855 - root - INFO - got prompt
2024-11-08 09:33:16,965 - ComfyUI_InstantIR_Wrapper.pipelines.sdxl_instantir - INFO - use lora alpha 1
2024-11-08 09:33:19,732 - ComfyUI_InstantIR_Wrapper.pipelines.sdxl_instantir - INFO - use lora alpha 8.0
2024-11-08 09:33:19,732 - peft.tuners.tuners_utils - INFO - Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
2024-11-08 09:33:25,699 - root - INFO - loading checkpoint done.
2024-11-08 09:33:26,031 - root - INFO - Start infer 1 images.
2024-11-08 09:33:29,632 - root - ERROR - !!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
2024-11-08 09:33:29,632 - root - ERROR - Traceback (most recent call last):
  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\sd-ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 147, in main
    ouput_img = instantIR_main(image_list, model, seed, creative_restoration, steps, prompt, negative_prompt, cfg,
  File "C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper\utils.py", line 175, in instantIR_main
    image = pipe(
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\sd-ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantIR_Wrapper\pipelines\sdxl_instantir.py", line 1518, in __call__
    cross_attention_emb = self.unet.time_embedding(cross_attention_t_emb, timestep_cond)
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\embeddings.py", line 376, in forward
    sample = self.linear_1(sample)
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\sd-ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

2024-11-08 09:33:29,652 - root - INFO - Prompt executed in 27.74 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":557,"last_link_id":959,"nodes":[{"id":503,"type":"LayerUtility: ImageScaleByAspectRatio V2","pos":{"0":3400,"1":-1050},"size":{"0":336,"1":330},"flags":{},"order":3,"mode":4,"inputs":[{"name":"image","type":"IMAGE","link":948,"shape":7,"label":"image"},{"name":"mask","type":"MASK","link":null,"shape":7,"label":"mask"}],"outputs":[{"name":"image","type":"IMAGE","links":[950,954],"slot_index":0,"label":"image"},{"name":"mask","type":"MASK","links":null,"label":"mask"},{"name":"original_size","type":"BOX","links":null,"label":"original_size"},{"name":"width","type":"INT","links":null,"label":"width"},{"name":"height","type":"INT","links":null,"label":"height"}],"properties":{"Node name for S&R":"LayerUtility: ImageScaleByAspectRatio V2"},"widgets_values":["original",1,1,"letterbox","lanczos","8","longest",1024,"#000000"],"color":"rgba(38, 73, 116, 0.7)"},{"id":531,"type":"Label (rgthree)","pos":{"0":5450,"1":-1150},"size":{"0":200.09765625,"1":50},"flags":{"allow_interaction":true},"order":0,"mode":0,"inputs":[],"outputs":[],"title":"InstantIR","properties":{"fontSize":50,"fontFamily":"Arial","fontColor":"#ffffff","textAlign":"left","backgroundColor":"transparent","padding":0,"borderRadius":0},"color":"#fff0","bgcolor":"#fff0"},{"id":553,"type":"LoadImage","pos":{"0":3010,"1":-1050},"size":[320,310],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[948],"slot_index":0,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["0 破损老照片.jpg","image"]},{"id":554,"type":"InstantIR_Loader","pos":{"0":3230,"1":-1360},"size":{"0":530,"1":230},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"InstantIR_MODEL","links":[953],"slot_index":0,"label":"model"}],"properties":{"Node name for S&R":"InstantIR_Loader"},"widgets_values":["3次元人\\juggernautXL_v9_V9 + RDPhoto 2国外.safetensors","C:\\sd-ComfyUI-aki-v1.3\\models\\InstantIR\\dino","models\\adapter.pt","models\\aggregator.pt","lcm-lora-sdxl.safetensors\\lcm-lora-sdxl.safetensors","models\\previewer_lora_weights.bin",true,true]},{"id":555,"type":"Get resolution [Crystools]","pos":{"0":3790,"1":-1050},"size":{"0":210,"1":100},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":950,"label":"image"}],"outputs":[{"name":"width","type":"INT","links":[955],"slot_index":0,"label":"width"},{"name":"height","type":"INT","links":[956],"slot_index":1,"label":"height"}],"properties":{"Node name for S&R":"Get resolution [Crystools]"}},{"id":556,"type":"InstantIR_Sampler","pos":{"0":4060,"1":-1360},"size":{"0":560,"1":470},"flags":{},"order":5,"mode":0,"inputs":[{"name":"model","type":"InstantIR_MODEL","link":953,"label":"model"},{"name":"pixels","type":"IMAGE","link":954,"label":"pixels"},{"name":"width","type":"INT","link":955,"widget":{"name":"width"},"label":"width"},{"name":"height","type":"INT","link":956,"widget":{"name":"height"},"label":"height"}],"outputs":[{"name":"image","type":"IMAGE","links":[959],"slot_index":0,"label":"image"}],"properties":{"Node name for S&R":"InstantIR_Sampler"},"widgets_values":["Photorealistic, highly detailed, hyper detailed photo - realistic maximum detail, 32k, ultra HD, extreme meticulous detailing, skin pore detailing, hyper sharpness, perfect without deformations, taken using a Canon EOS R camera, Cinematic, High Contrast, Color Grading. ","blurry, out of focus, unclear, depth of field, over-smooth, sketch, oil painting, cartoon, CG Style, 3D render, unreal engine, dirty, messy, worst quality, low quality, frames, painting, illustration, drawing, art, watermark, signature, jpeg artifacts, deformed, lowres",33314201,"randomize",20,7,true,768,768,0,1,1,true,true]},{"id":557,"type":"PreviewImage","pos":{"0":4690,"1":-1360},"size":{"0":710,"1":660},"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":959,"label":"images"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]}],"links":[[948,553,0,503,0,"IMAGE"],[950,503,0,555,0,"IMAGE"],[953,554,0,556,0,"InstantIR_MODEL"],[954,503,0,556,1,"IMAGE"],[955,555,0,556,2,"INT"],[956,555,1,556,3,"INT"],[959,556,0,557,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6727499949325871,"offset":[-2695.4540487855247,1809.4152291069258]},"workspace_info":{"id":"8Sf41WhALaDac0MKGvgfq"}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by smthemex** [comment]
Lowram mode,I haven't test it ,
Give me some time, I'll try to fix it

**Comment by xueqing0622** [comment]
3060 12G, 一般模式跑不了， low ram同样这个出错

**Comment by smthemex** [comment]
low ram 代码我还没有优化，迟点整吧 3060 12跑不了就奇怪 了，刚才我特意测试了一下，4070 12 跑没什么问题，就是慢。回头要把官方的代码拆了来优化加载流程。
还有，最好是先用SDXL的base底模测试，有些微调的SDXL模型可能删了clip或vae，测试如下:
![image](https://github.com/user-attachments/assets/2744c8db-c052-4e60-a57f-044167c09b46)

![image](https://github.com/user-attachments/assets/cc05fa81-7fbf-43ef-8e78-5a6d459a0a86)

**Comment by 2002erlinglinger** [comment]
> low ram 代码我还没有优化，迟点整吧 3060 12跑不了就奇怪 了，刚才我特意测试了一下，4070 12 跑没什么问题，就是慢。回头要把官方的代码拆了来优化加载流程。 还有，最好是先用SDXL的base底模测试，有些微调的SDXL模型可能删了clip或vae，测试如下: ![image](https://private-user-images.githubusercontent.com/138738845/384206502-2744c8db-c052-4e60-a57f-044167c09b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzM1MTksIm5iZiI6MTczMTA3MzIxOSwicGF0aCI6Ii8xMzg3Mzg4NDUvMzg0MjA2NTAyLTI3NDRjOGRiLWMwNTItNGU2MC1hNTdmLTA0NDE2N2MwOWI0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxMzQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGQwMTQ4NWM4Yzc5MWMxYTlhNmE4MDVlNjBkYmZlMTEzMmM2ZmM0MTE4ZDY0ZjkyZWVhNjA4MjI3ZDA0ZmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lUkxTDl25739XzZghOgRFe2oeMQ7ERq42GGXUWJ4y2Y)
> 
> ![image](https://private-user-images.githubusercontent.com/138738845/384206273-cc05fa81-7fbf-43ef-8e78-5a6d459a0a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzM1MTksIm5iZiI6MTczMTA3MzIxOSwicGF0aCI6Ii8xMzg3Mzg4NDUvMzg0MjA2MjczLWNjMDVmYTgxLTdmYmYtNDNlZi04ZTc4LTVhNmQ0NTlhMGE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxMzQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmYwY2VlMWI4MjAyZTNjNzU1ZGVlNjY3ZmYxOWU5NzI4YTFmNjQxNjkxZjY3ODJiYjU5MWJmMDI3NjJjYTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xcYjiyGLsB45zAGL4S6MQEE1Q8XB1QU-nzu2Z2UODpA)

I see. Thanks for your quick response.

**Comment by smthemex** [comment]
周日都在加班，所以下周吧，

**Comment by Orcsheepy** [comment]
菩萨，我也oom了，3060 12g，然后lowram也出错了，辛苦您修复一下：）
