### ISSUE TITLE
Missing Node Types

### ISSUE THREAD

**Issue by babajoe97** [smthemex/ComfyUI_InstantIR_Wrapper#7]
![Screenshot_10-11-2024_231828_127 0 0 1](https://github.com/user-attachments/assets/ec0c9b14-2028-4285-90fa-ddb7d7b9c1b3)

this screen apears when i import the workflow inside ComfyUI

**Comment by smthemex** [comment]
show  you console error

**Comment by chaaobhu126** [comment]
me too.console no error

**Comment by smthemex** [comment]
not this ,show the error which cause import fail  ,i can't find any error info   about this node in your console erro

**Comment by dmann73699** [comment]
## ComfyUI-Manager: installing dependencies done.
[2024-11-24 19:46:55.844] ** ComfyUI startup time: 2024-11-24 19:46:55.844202
[2024-11-24 19:46:55.844] ** Platform: Linux
[2024-11-24 19:46:55.844] ** Python version: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
[2024-11-24 19:46:55.844] ** Python executable: /debian/ComfyUI/venv/bin/python3
[2024-11-24 19:46:55.844] ** ComfyUI Path: /debian/ComfyUI
[2024-11-24 19:46:55.845] ** Log path: /debian/ComfyUI/comfyui.log
[2024-11-24 19:46:55.852] 
Prestartup times for custom nodes:
[2024-11-24 19:46:55.853]    0.0 seconds: /debian/ComfyUI/custom_nodes/rgthree-comfy
[2024-11-24 19:46:55.853]    0.2 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Pets
[2024-11-24 19:46:55.853]    3.7 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-11-24 19:46:55.853] 
Total VRAM 11936 MB, total RAM 64249 MB
[2024-11-24 19:46:57.300] pytorch version: 2.4.0+cu121
[2024-11-24 19:46:57.301] Set vram state to: NORMAL_VRAM
[2024-11-24 19:46:57.301] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-11-24 19:46:58.112] Using pytorch cross attention
[2024-11-24 19:46:58.928] [Prompt Server] web root: /debian/ComfyUI/web
[2024-11-24 19:46:59.128] /debian/ComfyUI/venv/lib/python3.11/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[2024-11-24 19:46:59.437] [95m[ComfyUI-0️⃣ 2️⃣ 4️⃣ 6️⃣ ] Topological Execution is detected.[0m
[2024-11-24 19:46:59.437] [95m[ComfyUI-0️⃣ 2️⃣ 4️⃣ 6️⃣ ] Loaded all nodes and apis.[0m
[2024-11-24 19:46:59.438] !!!3dphoto path was added to /debian/ComfyUI/venv/lib/python3.11/site-packages/3dphoto.pth
 if meet No module named 'MiDas' error,please restart comfyui
[2024-11-24 19:46:59.438] 3d-photo-inpainting use cache models,make sure your 'checkpoints' complete
[2024-11-24 19:46:59.507] [Crystools [0;32mINFO[0m] Crystools version: 1.18.4
[2024-11-24 19:46:59.522] [Crystools [0;32mINFO[0m] CPU: AMD Ryzen 9 3900X 12-Core Processor - Arch: x86_64 - OS: Linux 6.1.106-Unraid
[2024-11-24 19:46:59.522] [Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
[2024-11-24 19:46:59.522] [Crystools [0;32mINFO[0m] GPU/s:
[2024-11-24 19:46:59.522] [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 3060
[2024-11-24 19:46:59.522] [Crystools [0;32mINFO[0m] NVIDIA Driver: 565.57.01
[2024-11-24 19:47:00.334] ### Loading: ComfyUI-Impact-Pack (V7.8)
[2024-11-24 19:47:00.860] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[2024-11-24 19:47:00.878] [Impact Pack] Wildcards loading done.
[2024-11-24 19:47:00.879] ### Loading: ComfyUI-Inspire-Pack (V1.2.2)
[2024-11-24 19:47:00.922] Total VRAM 11936 MB, total RAM 64249 MB
[2024-11-24 19:47:00.922] pytorch version: 2.4.0+cu121
[2024-11-24 19:47:00.922] Set vram state to: NORMAL_VRAM
[2024-11-24 19:47:00.922] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-11-24 19:47:00.933] [94mtheUpsiders Logic Nodes: [92mLoaded[0m
[2024-11-24 19:47:00.934] ------------------------------------------
[2024-11-24 19:47:00.942] [34m### N-Suite Revision:[0m [32mae7cc848 [0m
[2024-11-24 19:47:00.942] Current version of packaging: 23.2
[2024-11-24 19:47:00.943] Version of cpuinfo: Not found
[2024-11-24 19:47:00.943] Current version of git: 3.1.41
[2024-11-24 19:47:00.943] Current version of moviepy: 1.0.3
[2024-11-24 19:47:00.943] Current version of cv2: 4.10.0
[2024-11-24 19:47:00.998] /debian/ComfyUI/venv/lib/python3.11/site-packages/skbuild/command/test.py:5: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
!!

        ********************************************************************************
        Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************

!!
  from setuptools.command.test import test as _test
[2024-11-24 19:47:00.998] Current version of skbuild: 0.17.6
[2024-11-24 19:47:00.998] Version of typing: Not found
[2024-11-24 19:47:01.002] Current version of diskcache: 5.6.3
[2024-11-24 19:47:01.010] Current version of llama_cpp: 0.2.26+cu121
[2024-11-24 19:47:01.010] Current version of timm: 1.0.9
[2024-11-24 19:47:01.398] Moondream error: You should probably run install_extra.bat (windows) or install transformers==4.36.2 in the enviroment.
 Also torch must be >= 2.1.0 (ERROR: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject)
[2024-11-24 19:47:01.425] Failed to auto update `Quality of Life Suit` 
[2024-11-24 19:47:01.426] [33mQualityOfLifeSuit_Omar92_DIR:[0m /debian/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
[2024-11-24 19:47:01.434] (pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
[2024-11-24 19:47:01.434] (pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[2024-11-24 19:47:01.446] ------------------------------------------
[2024-11-24 19:47:01.447] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
[2024-11-24 19:47:01.447] ------------------------------------------
[2024-11-24 19:47:01.447] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[2024-11-24 19:47:01.447] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[2024-11-24 19:47:01.447] ------------------------------------------
[2024-11-24 19:47:01.458] !!!VExpress path was added to /debian/ComfyUI/venv/lib/python3.11/site-packages/VExpress.pth
 if meet `No module` error,try `python main.py` again, don't be foolish to pip install modules
[2024-11-24 19:47:01.559] 
Fetching 19 files: 100%|██████████████████████| 19/19 [00:00<00:00, 2444.68it/s]
[2024-11-24 19:47:01.572] [92m[tinyterraNodes] [32mLoaded[0m
[2024-11-24 19:47:02.238] /debian/ComfyUI/venv/lib/python3.11/site-packages/albumentations/__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.17). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

[2024-11-24 19:47:02.840] [36;20m[comfy_mtb] | INFO -> loaded [96m83[0m nodes successfuly[0m
[2024-11-24 19:47:02.840] [36;20m[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://0.0.0.0,:::2940/mtb if you want more information.[0m
[2024-11-24 19:47:02.852] [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /debian/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
[2024-11-24 19:47:02.852] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[2024-11-24 19:47:02.852] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2024-11-24 19:47:02.872] 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
[2024-11-24 19:47:02.879] 
[2024-11-24 19:47:02.879] [92m[rgthree-comfy] Loaded 43 exciting nodes. 🎉[00m
[2024-11-24 19:47:02.879] 
[2024-11-24 19:47:03.205] 2024-11-24 19:47:03.205 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.calc
[2024-11-24 19:47:03.357] 2024-11-24 19:47:03.357 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.compose
[2024-11-24 19:47:03.720] 2024-11-24 19:47:03.720 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.create
[2024-11-24 19:47:03.833] 2024-11-24 19:47:03.833 | INFO     | Jovimetrix.sup.shader:<module>:113 -   vertex programs: 0
[2024-11-24 19:47:03.834] 2024-11-24 19:47:03.834 | INFO     | Jovimetrix.sup.shader:<module>:114 - fragment programs: 13
[2024-11-24 19:47:03.836] 2024-11-24 19:47:03.836 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.create_glsl
[2024-11-24 19:47:03.848] 2024-11-24 19:47:03.847 | ERROR    | Jovimetrix.sup.midi:midi_device_names:48 - midi devices are offline
[2024-11-24 19:47:03.848] 2024-11-24 19:47:03.848 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.device_midi
[2024-11-24 19:47:03.850] 2024-11-24 19:47:03.850 | ERROR    | Jovimetrix.sup.stream:<module>:36 - NO SPOUT GL SUPPORT
[2024-11-24 19:47:03.851] 2024-11-24 19:47:03.851 | ERROR    | Jovimetrix.sup.stream:<module>:37 - No module named 'SpoutGL'
[2024-11-24 19:47:03.851] 2024-11-24 19:47:03.851 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.device_stream
[2024-11-24 19:47:03.853] 2024-11-24 19:47:03.852 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.utility.batch
[2024-11-24 19:47:03.853] 2024-11-24 19:47:03.853 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.utility.info
[2024-11-24 19:47:03.853] 2024-11-24 19:47:03.853 | WARNING  | Jovimetrix.core.utility.io:<module>:42 - no gifski support
[2024-11-24 19:47:03.854] 2024-11-24 19:47:03.854 | INFO     | Jovimetrix:__init__:987 - ✅ Jovimetrix.core.utility.io
[2024-11-24 19:47:03.854] 2024-11-24 19:47:03.854 | INFO     | Jovimetrix:__init__:988 - 63 nodes loaded
[2024-11-24 19:47:04.225] ### Loading: ComfyUI-Manager (V2.51.9)
[2024-11-24 19:47:04.258] ### ComfyUI Revision: 2859 [b4526d3f] | Released on '2024-11-24'
[2024-11-24 19:47:04.333] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-11-24 19:47:04.342] Traceback (most recent call last):
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/models/clip/image_processing_clip.py", line 21, in <module>
    from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/image_transforms.py", line 50, in <module>
    import tensorflow as tf
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/python/autograph/core/ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/python/autograph/utils/__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/python/autograph/utils/context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 57, in <module>
    from tensorflow.python.framework import tensor as tensor_lib
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/python/framework/tensor.py", line 35, in <module>
    from tensorflow.python.framework import tensor_util
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/tensorflow/python/framework/tensor_util.py", line 35, in <module>
    from tensorflow.python.framework import fast_tensor_util
  File "tensorflow/python/framework/fast_tensor_util.pyx", line 1, in init tensorflow.python.framework.fast_tensor_util
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/debian/ComfyUI/nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/debian/ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper/__init__.py", line 2, in <module>
    from .InstantIR_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/debian/ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper/InstantIR_node.py", line 9, in <module>
    from .utils import load_list_images, tensor2imglist, tensor_upscale,instantIR_main, instantIR_load_model, auto_downlaod,clear_memory
  File "/debian/ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper/utils.py", line 13, in <module>
    from .pipelines.sdxl_instantir import InstantIRPipeline
  File "/debian/ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper/pipelines/sdxl_instantir.py", line 23, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1767, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/debian/ComfyUI/venv/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

[2024-11-24 19:47:04.342] Cannot import /debian/ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper module for custom nodes: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
[2024-11-24 19:47:04.343] 
Import times for custom nodes:
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/SDXLAspectRatio.py
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Crystools-save
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Image-Selector
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-portrait-master-zh-cn
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_SSStereoscope
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/image-resize-comfyui
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/LoadLoraWithTags
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Stereopsis
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/sdxl-recommended-res-calc
[2024-11-24 19:47:04.343]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_Noise
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/sdxl_prompt_styler
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/sd-dynamic-thresholding
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/cg-use-everywhere
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/websocket_image_save.py
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Logic
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-SAI_API
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/stability-ComfyUI-nodes
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfy-image-saver
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_Cutoff
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/sd-perturbed-attention
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-YOLO
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-MakeFrame
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/masquerade-nodes-comfyui
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-RAVE
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-ollama-prompt-encode
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyStereo
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUi_PromptStylers
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-3d-photo-inpainting
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Pets
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Tripo
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui_face_parsing
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-ollama-nodes
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Video-Matting
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-portrait-master
[2024-11-24 19:47:04.344]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Text_Image-Composite
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_DDColor
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/virtuoso-nodes
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-browser
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/mikey_nodes
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-various
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_essentials
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyMath
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui-dream-video-batches
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/rgthree-comfy
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-KJNodes
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/efficiency-nodes-comfyui
[2024-11-24 19:47:04.345]    0.0 seconds: /debian/ComfyUI/custom_nodes/trNodes
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-0246
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-11-24 19:47:04.346]    0.0 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
[2024-11-24 19:47:04.346]    0.1 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Crystools
[2024-11-24 19:47:04.346]    0.1 seconds (IMPORT FAILED): /debian/ComfyUI/custom_nodes/ComfyUI_InstantIR_Wrapper
[2024-11-24 19:47:04.346]    0.1 seconds: /debian/ComfyUI/custom_nodes/ComfyUI_V-Express
[2024-11-24 19:47:04.346]    0.1 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Gemini
[2024-11-24 19:47:04.346]    0.2 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Flowty-TripoSR
[2024-11-24 19:47:04.346]    0.4 seconds: /debian/ComfyUI/custom_nodes/comfyui-ollama
[2024-11-24 19:47:04.346]    0.5 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-N-Nodes
[2024-11-24 19:47:04.346]    0.5 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-DDColor
[2024-11-24 19:47:04.347]    0.5 seconds: /debian/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
[2024-11-24 19:47:04.347]    1.0 seconds: /debian/ComfyUI/custom_nodes/Jovimetrix
[2024-11-24 19:47:04.347]    1.2 seconds: /debian/ComfyUI/custom_nodes/comfy_mtb
[2024-11-24 19:47:04.347] 
[2024-11-24 19:47:04.358] Starting server

[2024-11-24 19:47:04.358] To see the GUI go to: http://0.0.0.0:2940
[2024-11-24 19:47:04.358] To see the GUI go to: http://[::]:2940
[2024-11-24 19:47:04.386] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-11-24 19:47:04.389] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-11-24 19:47:04.427] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-11-24 19:47:04.467] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by smthemex** [comment]
it's look like transformer version  or  check your env ' numpy, 
try:
 pip untinstall numpy  and pip install numpy==1.26.4
or try 
pip uninstall transformers  and pip install transformers == 4.36.2

**Comment by dmann73699** [comment]
I think pip install numpy==1.26.4 fixed it. thanks
